### ISSUE TITLE
Deployment fehlgeschlagen

### ISSUE THREAD

**Issue by 205er** [ToolboxBodensee/toolbox-webseite#107]
Die aktuelle Version der TB-Website wurde nicht automatisch deployt.
https://travis-ci.org/ToolboxBodensee/toolbox-webseite/builds

**Comment by ottojo** [comment]
Wird heute Abend gefixt

**Comment by DO1JLR** [comment]
https://travis-ci.org/ToolboxBodensee/toolbox-webseite/jobs/447805033
Ist gefixt
