### ISSUE TITLE
Fuckup in der Menüverlinkung

### ISSUE THREAD

**Issue by 205er** [ToolboxBodensee/toolbox-webseite#109]
Mir ist aufgefallen, dass die Verlinkung im Menü entweder irreführend oder fehlerhaft ist:

- Klick auf "_Verein_" führt auf die Seite "_Vereinsheim_"
- Klick auf "_Verein_"-->"_Mitgliedschaft_" führt auf die Seite "_Verein_"
- Verweis auf die Seite "_Mitgliedschaft_" (sollte diese überhaupt existieren) fehlt

**Comment by DO1JLR** [comment]
@205er Wie wäre denn dein Vorschlag um das besser zu machen?

**Comment by 205er** [comment]
- Die Logos gehören eher nach "Presse" verschoben.
- den Menüpunkt "Mitgliedschaft" ersatzlos streichen, wenn es keine zugehörige Seite dazu gibt.
- Seite "Verein" ersatzlos streichen; der Inhalt ist bereits auf anderen Seiten enthalten.

Oder?

**Comment by maxbachmann** [comment]
Ich habe die Vorschläge mal übernommen
