### ISSUE TITLE
kaputter textumbruch im menü auf smartphone

### ISSUE THREAD

**Issue by DEvil0000** [ToolboxBodensee/toolbox-webseite#112]
im menü werden auf meinem smartphone lange titel umgebrochen. sieht aber falsch aus und texte überlappen einander.
edit:
android: chrome

**Comment by DO1JLR** [comment]
Wird durch https://github.com/ToolboxBodensee/toolbox-webseite/pull/95/commits/d63633ec29703d2d080e7544e0ee0f5537dea918 gelöst.

**Comment by DEvil0000** [comment]
danke, works
