### ISSUE TITLE
Webseite auf Chinesisch Übersetzen

### ISSUE THREAD

**Issue by DO1JLR** [ToolboxBodensee/toolbox-webseite#130]
Wie @205er [hier](https://github.com/ToolboxBodensee/toolbox-webseite/pull/127#pullrequestreview-171012769) vorgeschlagen hat, wäre eine Übersetzung der Toolbox Webseite ins Chinesische sicherlich wünschenswert.

Immerhin sind wir gelegendlich treue Kunden bei Aliexpress und es schadet bestimmt nicht die Internationalen Geschäftsbeziehungen durch eine Übersetzung der Seite verbessern zu wollen.

Config Sniped:
```
toolbox-webseite.lektorproject
------------------------------------
[alternatives.cn]
name = Chinese
locale = zh_CN
url_prefix = /cn/
```

**Comment by maxbachmann** [comment]
Haben wir hier irgendjemand der chinesisch kann? Bei englisch ist das ja noch irgendwie prüfbar aber eine random translator Übersetzung ins chinesische schenke ich nicht all zu viel vertrauen ^^

**Comment by DO1JLR** [comment]
#154
