### ISSUE TITLE
gekürzte Projektliste

### ISSUE THREAD

**Issue by maxbachmann** [ToolboxBodensee/toolbox-webseite#131]
Wir haben in der Navigationsleiste zur Übersichtlichkeit nur eine gekürzte Projektliste. Das finde ich auch gut, allerdings zeigt diese die ältesten Projekte an --> es werden immer die gleichen bleiben.
Sinnvoller wäre es hier nur die Neusten zu zeigen

**Comment by DO1JLR** [comment]
![screenshot_2018-11-02 projects](https://user-images.githubusercontent.com/16953664/47926668-676c3800-dec1-11e8-8acf-e718243668a1.png)
Meiner Auffassung nach sind LED-Steuerung, Mutteruhrsteuerung [...] C3WOC die neusten Projekte (siehe Screenshot)

**Comment by maxbachmann** [comment]
ja ist mir auch gerade aufgefallen hat nur bei mir offline mit Lektor irgendwie das neue Projekt erst unten eingefügt. Nach einer erneuten Veränderung hat es dann aber gepasst

**Comment by DO1JLR** [comment]
Die Projekte werden anhand des Datums sortiert. Hat ein Projekt noch kein Datum oder ein etwas älteres, landet es eben etwas weiter unten in der Liste!
