### ISSUE TITLE
inline

### ISSUE THREAD

**Issue by maxbachmann** [ToolboxBodensee/toolbox-webseite#148]
Wir nutzen aktuell noch häufig inline. Es wäre vielleicht ganz cool das immer weiter zu reduzieren :)

**Comment by maxbachmann** [comment]
zumindest css sollte jetzt nirgends mehr inline sein. Es gibt weiterhin einige inline scripts die auch noch ausgelagert werden sollen

**Comment by DO1JLR** [comment]
Super Arbeit von dir @maxbachmann , danke!
