### ISSUE TITLE
Programm für TdoT -> Vortrag MQTT richtiger Titel

### ISSUE THREAD

**Issue by oldwired** [ToolboxBodensee/toolbox-webseite#160]
https://toolbox-bodensee.de/blog/tag-der-offenen-tuere-2018/

statt nur MQTT bitte "Einführung in das IoT-Protokoll MQTT" - das sagt dann etwas mehr aus.

**Comment by DO1JLR** [comment]
Zu einen Pull-Request bist du nicht zu motivieren @oldwired?
Schon gut,m ich mach das mal eben!

**Comment by DO1JLR** [comment]
@oldwired Bitte den Pull Request #161 reviewen!

**Comment by DO1JLR** [comment]
Ohne Review einer zweiten Person ist es aktuell leider nicht mehr möglich etwas auf die Webseite zu packen! @oldwired: Du bist jetzt dran!
