### ISSUE TITLE
Spenden-Seite implementieren

### ISSUE THREAD

**Issue by blaues0cke** [ToolboxBodensee/toolbox-webseite#163]
Früher hatten wir mal eine Spenden-Seite auf der Stand, wie man uns Geld spenden kann und wie unsere Kontodaten lauten. Wir müssen bei Gelegenheit prüfen, ob uns Leute überhaupt einfach so Geld spenden können (@tschanne ?) und diese Seite ggf. wieder online nehmen.

**Comment by maxbachmann** [comment]
Toolbox Bankaccount: DE34690500010024979734

**Comment by DO1JLR** [comment]
#198
