### ISSUE TITLE
Meta- und Open-Graph-Tags implementieren

### ISSUE THREAD

**Issue by blaues0cke** [ToolboxBodensee/toolbox-webseite#164]
Damit das Sharing besser aussieht sollten wir Meta- und OG-Tags korrekt/besser implementieren, siehe dazu ggf. auch:

http://ogp.me/

![image](https://user-images.githubusercontent.com/5159398/48604274-98487480-e979-11e8-8dc2-dee7a2c42a41.png)

**Comment by davidblumer** [comment]
![image](https://user-images.githubusercontent.com/13996650/52916728-7dbcc900-32e3-11e9-8610-0ea186face45.png)

I created a og:image, someone who knows lektor can add it to the headers pls.

**Comment by DO1JLR** [comment]
@davidblumer Any progress here?

I am not deep enough in the topic to give here real support. But if you want to add specific content to the HEADER Part of the Website, you have to add it to https://github.com/ToolboxBodensee/toolbox-webseite/blob/master/templates/layout.html probably.
