### ISSUE TITLE
Sponsoren erwähnen

### ISSUE THREAD

**Issue by blaues0cke** [ToolboxBodensee/toolbox-webseite#165]
Vielleicht sollten wir das (prominent) tun

**Comment by DO1JLR** [comment]
Mit @tschanne hatten wir mal das Gespräch über Mitglieder und/oder Sponsoren auf der Webseite erwähnen. IIRC meinte da @tschanne, das wohl einige Sponsoren garnicht erwähnt werden wollen???

**Comment by blaues0cke** [comment]
Das stimmt, vielleicht sollten wir hier nochmal nachhören. Wobei ich bei SAP und Wagner schon davon ausgehe, dass die das wollen - wir haben ja auch schon aktiv gemeinsame Presseartikel provoziert :-) 

(Unser damaliger Vermieter wollte das beispielsweise nicht)

**Comment by DO1JLR** [comment]
Ping @blaues0cke, gibt es hier Updates?

**Comment by DO1JLR** [comment]
Closed weil keine Updates... @blaues0cke ?
