### ISSUE TITLE
the picture lists have problems with positioning

### ISSUE THREAD

**Issue by maxbachmann** [ToolboxBodensee/toolbox-webseite#172]
The picture lists that are included with some parts of the webpage like some of the project pages do not properly resize and position.
For most screen sizes thats no big problem since it´s just not in the mid, but on the mobile the pictures are still bigger than the screen

so it would be nice when they are never bigger than the screen size
the list is always positioned in the mid
the javascript for those images still has a lot of inline js which would be nice to move out

**Comment by DO1JLR** [comment]
@maxbachmann Any new information or progress here?

**Comment by maxbachmann** [comment]
#still-broken o.0
