### ISSUE TITLE
button columns do not have breakpoints

### ISSUE THREAD

**Issue by maxbachmann** [ToolboxBodensee/toolbox-webseite#173]
Right now on small devices the text in buttons will get to big for them and interferes with other stuff

So it would be nice when
1) columns count gets smaller on smaller screens (like it´s done for the imagelists)
2) the text in buttons either gets smaller, splitted into multiple files or the overflow get´s hidden

**Comment by DO1JLR** [comment]
Looks like you need to do some sass magic here.

I heard @maxbachmann is the real pro in this topic!
