### ISSUE TITLE
social media table on contact page

### ISSUE THREAD

**Issue by maxbachmann** [ToolboxBodensee/toolbox-webseite#174]
the social media table is to big for the position on small screens, so it is required to do a horizontal scroll

would be nice when at a breakpoint the view changes from

1 | 2
\------
1 | 2

to 

1
\--
2
\--
1
\--
2

**Comment by DO1JLR** [comment]
Puh, da fehlen mir echt die css skills um das umzusetzen...

**Comment by DO1JLR** [comment]
@maxbachmann Hast du eine Idee wie man das umsetzen könnte?

**Comment by DO1JLR** [comment]
Wegen inaktivität geschlossen
