### ISSUE TITLE
Display opening hours 

### ISSUE THREAD

**Issue by haekelhexe** [ToolboxBodensee/toolbox-webseite#179]
As a stranger to the page it is not instantly obvious to me when the Toolbox is open. 
The status only says "open" or "closed". As we're not "open" very often it appears that the Toolbox is "closed" constantly. And it is not very easy to find the information on when someone's there.
Suggestion: Mouseover with opening hours for the status 
OR link to the opening hours information
OR another easy hint for strangers ;-)

**Comment by phschoen** [comment]
see pullrequest #180
