### ISSUE TITLE
Navigation overlapping gallery controls

### ISSUE THREAD

**Issue by ottojo** [ToolboxBodensee/toolbox-webseite#182]
Navigation overlaps the image and gallery controls in the top right corner
(Visible [here](https://toolbox-bodensee.de/projekte/toolboxplane/#lg=1&slide=0) for example)

**Comment by DO1JLR** [comment]
Da muss man wohl einen besseren z-index wert für das menü finden... Oder für die Galerie...
@ottojo oder @maxbachmann, wollt ihr mal schauen?

**Comment by maxbachmann** [comment]
ja müssen wir schauen habe den mal einfach ziemlich hoch gestellt, da die map so viele elemente hat. ka was der aktuelle zindex der Galerie ist. Werde jetzt vor Weihnachten aber wohl nicht mehr dazukommen mir das anzuschauen. Danach schaue ich mir das gerne mal an.

**Comment by maxbachmann** [comment]
fixed with raised zindex
