### ISSUE TITLE
startpage breakpoints

### ISSUE THREAD

**Issue by maxbachmann** [ToolboxBodensee/toolbox-webseite#194]
Auf manchen Bildschirmgrößen wird der Text einiger sections immer noch abgeschnitten

**Comment by DO1JLR** [comment]
Beispiele?

**Comment by maxbachmann** [comment]
![bildschirmfoto vom 2019-01-04 15-24-12](https://user-images.githubusercontent.com/44199644/50692624-d3d7f480-1034-11e9-94b0-be894eb38183.png)

**Comment by DO1JLR** [comment]
Und hast du eine Idee zur Lösung @maxbachmann ?

**Comment by maxbachmann** [comment]
auch die erste section verschiebt sich in einigen Größen
