### ISSUE TITLE
debugging video floppyorgel

### ISSUE THREAD

**Issue by maxbachmann** [ToolboxBodensee/toolbox-webseite#195]
Das eingebundene Video auf der Floppyorgel Projektseite passt sich nicht der Bildschirmgröße an

**Comment by maxbachmann** [comment]
d

**Comment by DO1JLR** [comment]
Ach, du meinst das .webm... Sag das doch!

**Comment by maxbachmann** [comment]
ok hätte ich näher spezifizieren können ^^

**Comment by DO1JLR** [comment]
Ich finde das webm da nicht wirklich ein Problem.

Aber sonst schau dir doch mal https://videojs.com/ an!

**Comment by maxbachmann** [comment]
das war doch gar nicht das Problem sondern nur die Größe. Das hat mit dem Dateityp nichts zu tun ;)
