### ISSUE TITLE
CSS automatisch bauen

### ISSUE THREAD

**Issue by DO1JLR** [ToolboxBodensee/toolbox-webseite#220]
Wie in #217 vorgeschlagen, könnte man die Überlegung wieder aufnehmen, das CSS automatisch zu bauen.

Dabei gibt es dann ein paar kleine Schwirigkeiten, die sich aber relativ leicht lösen oder ignorieren lassen.
Das wäre zum Beispiel, dass die CSS Datei nicht mit ``"https://toolbox-bodensee.de/css/main.css"`` eingebunden ist, sondern als ``"/css/main.css"``.
Das würde ich auch ganz gerne so machen, aber die lokale Lektor Version braucht dann doch die CSS Datei.

Man könnte natürlich vorschreiben, dass über ``make server`` oder so lektor gestartet werden muss, da dabei das CSS generiert werden könnte. Aber dann verlieren wir potentiel die einfache handlung, da nun auch sassc überall mit installiert werden muss. Und bis lektor installiert ist, ist das für manche schon ein Hexenwerk!
Möglicherweise hat lektor eine variable, mit der im template ein anderes aussehen auf dem produktivsystem zu sehen ist als im lokalen server. Aber das ist geraten und wunschdenken.

**Comment by fbsb** [comment]
Der beste Ansatz hierfür wäre die Lektors-Webpack Integration zu nutzen und alle Assets (CSS, JS, Images, Fonts, etc) beim starten des Lektor-Servers zu bauen (siehe [hier](https://www.getlektor.com/docs/guides/webpack/)) 

`lektor server -f webpack`

Hab schon vor einiger Zeit damit begonnen (daher die Docker-Integration), doch die ganzen Assets Webpack-kompatibel zu machen benötigt viel Zeit und die fehlt mir Zurzeit. Gerne könnte ich den ersten Schritt machen und die Webpack-Integration umstellen, sodass jemand anderes die Migration/Anpassung der Assets übernehmen kann.

Außerdem wird es Kompatibilitätsprobleme mit den aktuellen Deployment-Workflow geben und das ganze Staging/Prod Deployment müsste angepasst werden (was genau, weiß ich noch nicht). 

Wir könnten mal an einem Abend das Ganze etwas genauer besprechen (zum Beispiel am kommenden Donnerstag, den 14.02) ob der Aufwand sich lohnt und schauen wie wir die Deployment-Probleme lösen können.

**Comment by DO1JLR** [comment]
Resolved with #229
