### ISSUE TITLE
Datenschutzangaben überarbeiten

### ISSUE THREAD

**Issue by DO1JLR** [ToolboxBodensee/toolbox-webseite#235]
In der [DSGVO](https://dsgvo-gesetz.de/art-12-dsgvo/) steht, dass Informationen ``in präziser, transparenter, verständlicher und leicht zugänglicher Form in einer klaren und einfachen Sprache`` zu übermitteln sind.

Daher wären zwei sachen Sinnvoll:

1. Die genaue auflistung, welche drittquellen wir alles verwenden.
  *Aus dem stehgreif fallen mir da neben youtube noch titles.ffbsee.de, openstreetmap, möglicherweise c3woc.de und invidio.us ein.

2. Das übersetzen der Datenschutzhinweise in [Einfache Sprache](https://de.wikipedia.org/wiki/Leichte_Sprache) wäre denkbar... aber natürlich nicht zwingend notwendig.

3. Etwas illustration mit Bildern und Grafiken? Eventuell???

**Comment by 205er** [comment]
Moin,

zu 1.
ich stelle es mir schwierig vor, die "Drittquellen" aktuell zu halten. Es kommen ja ständig irgendwelche Blogposts hinzu, die ggf. irgendwo hin verweisen oder gar externen Content einbinden. Wer soll das überwachen und hier ergänzen? Vermutlich ist's einfacher, wenn wir das allgemein formulieren (bzw. so lassen wie's aktuell ist) oder irgendwie automatisiert zusammenfassen.

zu 2.
Was ist denn an den verwendeten Formulierungen so schwer zu verstehen? Sehe da keine Notwendigkeit, weil hier keine umständlichen Ausdrucksweise zu finden ist... Ggf. verwirrt der Cookie-Ausschweif etwas und führt beim Leser zu Irritationen.

zu 3.
Die Datenschutzerklärung zu visualisieren? Das wäre mal ein interessanter Ansatz!

**Comment by maxbachmann** [comment]
1) es mag schon sein, dass das mit Blogposts schwer aktuell zu, aber gerade die oben genannten werden doch recht viel eingesetzt.
2) Ich denke auch nicht dass das nötig ist. Da ist wie von @205er erwähnt am ehesten der Text zu cookies verwirrend, auch wenn der micht jetzt auch nicht wirklich stört.
3) Grafiken sollten generell zu einem besseren Verständnis beitragen. Ich sehe allerdings unserer Datenschutzerklärung nicht wirklich Teile die mithilfe von Grafiken schneller/besser zu erfassen wären. Wo siehst du da Potential für den Einsatz von Grafiken @DO1JLR?

**Comment by DO1JLR** [comment]
>
>     3. Grafiken sollten generell zu einem besseren Verständnis beitragen. Ich sehe allerdings unserer Datenschutzerklärung nicht wirklich Teile die mithilfe von Grafiken schneller/besser zu erfassen wären. Wo siehst du da Potential für den Einsatz von Grafiken @DO1JLR?

War nur eine Idee... So ein richtiges Bild dazu habe ich nicht. Eher ein vager Gedanke, den ich aber nicht ganz formuliert oder gezeichnet bekomme...

**Comment by DO1JLR** [comment]
wontfix
