### ISSUE TITLE
The 'section'-element gets a inactive-class when the page is refreshed. Which is why the projekt page is not displayed after refreshing.

### ISSUE THREAD

**Issue by DO1JLR** [ToolboxBodensee/toolbox-webseite#240]
Mir ist kürzlich aufgefallen, dass [die Projektseite](https://toolbox-bodensee.de/projekte/) irgendwie erst Inhalt anzeigt, solbald man anfängt bei ihr nach unten  zu scrollen.

Das scheint an irgend einer Javascript-gesteuerten Animation zu liegen, denn wenn ich Scripte generell verbiete, ist das Problem nicht vorhanden.

Das Problem tritt unter Firefox auf dem Desktop-Computer auf.
Kann das jemand replizieren? Hat jemand anhnung, woran das liegt?

**Comment by 205er** [comment]
ich kann das Problem  weder mit Firefox noch mit Chrome nachvollziehen...

**Comment by DO1JLR** [comment]
Ich werde das mal in der Toolbox an den Computern ausprobieren!

**Comment by davidblumer** [comment]
cannot reproduce

**Comment by DO1JLR** [comment]
Habe das soeben unter WIndows 10 wie folgt reproduzieren können:

+ Google Chrome: funktioniert alles
+ MS Edge: Der Aufruf der Projektseite klappt. Lädt man dann die Seite neu, ist sie so lange leer, bis man anfängt zu scrollen!
+ Firefox: Wie bei MS Edge

**Comment by davidblumer** [comment]
The 'section'-element gets a inactive-class when the page is refreshed. Which is why its not dispayed

**Comment by DO1JLR** [comment]
@davidblumer Any Idea how to fix this?

**Comment by maxbachmann** [comment]
I can reproduce this aswell in firefox

**Comment by DO1JLR** [comment]
Ab Zeile 170 scheint das [/js/main.js](https://github.com/ToolboxBodensee/toolbox-webseite/blob/master/assets/js/main.js#172) dieses inaktiv einzusetzen... aber so ganz schau ich da nich durch.
