### ISSUE TITLE
navigation bar disappears

### ISSUE THREAD

**Issue by maxbachmann** [ToolboxBodensee/toolbox-webseite#261]
on the project page the navigation bar disappears on the mobile page

**Comment by DO1JLR** [comment]
Yes, because we removed the JS because it is broken!

**Comment by maxbachmann** [comment]
true forgot that. Still needs to be mentioned in a issue so someone might fix it ;)

**Comment by DO1JLR** [comment]
Hopefully...

**Comment by maxbachmann** [comment]
At least it bugs us more ^^

**Comment by maxbachmann** [comment]
it's still broken lmao ...

**Comment by DO1JLR** [comment]
Yeah, sorry. Forgot to remove it!
