### ISSUE TITLE
Make fails on laptop from @haekelhexe

### ISSUE THREAD

**Issue by DO1JLR** [ToolboxBodensee/toolbox-webseite#296]
Make fails on laptop from @haekelhexe .

The Issue is, that the system packet manager don't can find nodejs or yarn.
And then it won't install any packages because apt failed finding all requirements.

An other Issue was, that the system don't can find pip, because only pip3 and pip3.7 are installed (manually during debugging).

I tried to fix it in PR #288 but it will take a little bit more time until it is fixed.

Here is the Issue to remind you, THAT THIS IS A URGENT.

Currently the installation fails on some devices.

PLEASE FIX SOON!

**Comment by maxbachmann** [comment]
whats the system?

**Comment by DO1JLR** [comment]
> whats the system?

I don't know. Something debian-based. Maybe Ubuntu-isch or Linux Mint?
