### ISSUE TITLE
Menüpunkte klarer gestalten

### ISSUE THREAD

**Issue by drwuro** [ToolboxBodensee/toolbox-webseite#338]
- was mich schon länger etwas stört: Der Punkt "Alle Projekte" geht etwas unter, weil er sich nicht abhebt von den restlichen Menüpunkten. Es gäbe die folgenden Möglichkeiten um dies zu verbessern (evtl auch mehrere davon gleichzeitig):

  - vom Schriftbild her anders gestalten, z.B. "alle Projekte..." (mit kleinem a und "..." am Ende) oder z.B. mit eckigen Klammern, also z.B. "[Alle Projekte...]"
  - komplett umbenennen in z.B. "alle..." oder "mehr..."
  - ganz nach oben setzen statt an zweitletzte Stelle
  - farblich hervorheben (so wie z.B. "Mitglied werden" im Menü "Verein" - aber: siehe unten)

- was mir aufgefallen ist: Das Menü "Blog" hat keinen vergleichebaren Menüpunkt, also kein "alle Blog-Einträge..." oder sowas. Klar, wenn man direkt auf "Blog" klickt, bekommt man das, ich wäre aber dafür die Menüs einheitlicher zu gestalten

- was mir noch aufgefallen ist: Der Menüpunkt "Mitglied werden" hebt sich vom Design her so stark heraus, dass er schon fast wie eine Überschrift wirkt für die folgenden Punkte, und nicht wie ein Menüpunkt selbst. Vielleicht könnte man diesen etwas weniger krass anders gestalten

was meint ihr dazu?

**Comment by maxbachmann** [comment]
der ist bei den Blogeinträgen nur vergessen worden (habe ich kurz ergänzt)

Allgemein ja das Menü kann sicher etwas Überarbeitung gebrauchen.
Ich habe das Layout am Wochenende in der Bedienung erleichtert, so dass das jetzt problemlos entsprechend umgeändert werden kann.
https://github.com/ToolboxBodensee/toolbox-webseite/blob/master/databags/navigation.ini
beinhaltet alle Übersetzungen
https://github.com/ToolboxBodensee/toolbox-webseite/blob/master/databags/nav-bar.ini
das Grundsätzliche Layout des Menüs (kommt die nächsten Tage auch noch etwas Doku dazu)

Dementsprechend könnte da jetzt auch relativ einfach etwas experimentiert werden.

Bezüglich deiner Vorschläge:
Finde ich sind einige interessante Ideen, die ich (oder vielleicht auch du) die nächsten Tag mal ausprobieren könnten was tatsächlich etwas hilft.

**Comment by drwuro** [comment]
ok vielen dank, werde da auch mal rumprobieren :)

**Comment by drwuro** [comment]
habe es jetzt mal umbenannt in " - Alle Projekte - " usw, denke das ist erstmal ok, zumindest mir gefaellts. daher werd ich die issue mal zumachen :) falls jemand ne bessere idee hat kann mans natuerlich immer noch anpassen
