### ISSUE TITLE
deploy pull requests

### ISSUE THREAD

**Issue by maxbachmann** [ToolboxBodensee/toolbox-webseite#342]
@ottojo Ich will mich jetzt mal daran machen die pull requests auf einem Server wieder zum laufen zu bekommen.
Wie hat das mit den environment Variablen damals funktioniert? Ich meine externe pullrequests dürften laut: https://docs.travis-ci.com/user/pull-requests/
gar keinen Zugriff auf unsere geheimen Variablen haben.

**Comment by DO1JLR** [comment]
Du möchtest das eventuell anders machen. 

Quasi dass du nicht travis bauen lässt und dann den Pull Request deployst sondern dass du dir eine API (oder so) bastelst, der du sagst: Hol dir mal den PR #420 und baue ihn. Schreib dass dan in die Kommentare. 

Dann werden auch keine Secret Keys oder token geleaked. Außer du verschleierst deine API damit.

**Comment by maxbachmann** [comment]
das mag schon sein. Ich würde aber gerne erst das Problem verstehen bevor ich da irgendwas anderes baue.
 Denn mir ist ehrlich gesagt schon mehr als schleierhaft wie das überhaupt funktioniert hat, dass travis externe pullrequests so gepusht hat, da da gar kein Zugriff auf die Variablen bestehen darf. 
Ich kann das so nicht mehr nachvollziehen, aber das darf eigentlich nur unter zwei Bedingungen passieren:
a) die variablen waren nicht auf geheim gestellt
b) der Pullrequest war nicht extern

Aber ja danach möchte ich das vermutlich anders machen
