### ISSUE TITLE
thumbnails von bildergalerien einheitlicher / schöner darstellen?

### ISSUE THREAD

**Issue by drwuro** [ToolboxBodensee/toolbox-webseite#353]
wenn in einer bildgeralerie bilder mit unterschiedlichen seitenverhältnissen vorhanden sind, sieht die vorschau der thumbnails etwas chaotisch aus. vielleicht gibt es eine möglichkeit, diese etwas geordneter anzuzeigen, z.b. indem man die thumbnails automatisch auf eine einheitliche größe croppen lässt. nachteil ist natürlich, dass dann der thumbnail nicht mehr die volle information anzeigt, was in manchen fällen doof aussehen könnte. eine andere lösung wäre es, eine einheitliche höhe festzulegen, nachteil wäre dann dass hochformatige bilder einen deutlich kleineren thumbnail bekommen.

was wäre eure meinung hierzu?

**Comment by maxbachmann** [comment]
Ich werde das in den nächsten Wochen nochmal überarbeiten um den webp support zu ergänzen und habe auch vor einigen Tagen mal die Breakpoints dafür eingefügt. Aktuell läuft hier halt alles über die Breite und die Höhe kann jedes Bild grundsätzlich so wählen wie es will.
Dass das aktuell teilweise sehr chaotisch aussieht befinde ich ebenfalls, wobei ich an der Stelle natürlich auch nicht sicher bin ob es doof aussieht die Bilder auf eine einheitliche Höhe zu begrenzen (insbesonder bin ich mir da auch nicht so sicher an was für einer Höhe man sich da am Besten orientiert)

**Comment by drwuro** [comment]
habe gerade ein bisschen damit rumexperimentiert; ist gar nicht so einfach, vor allem wenn es auf dem handy auch gut aussehen soll. werde mal noch weiter schauen obs noch andere moeglichkeiten gibt

**Comment by maxbachmann** [comment]
absolut o.0
Du kannst natürlich auch entsprechende Breakpoints nutzen wie in dem anderen issue erklärt, so dass du nicht auf dem Handy und auf dem normalen Monitor das gleiche Design nutzt

**Comment by drwuro** [comment]
habe jetzt evtl ne loesung ;) muss nur noch schauen dass ich das alles lokal gebuildet bekomme

**Comment by drwuro** [comment]
hab jetzt mal ne loesung gefunden und committed, daher wuerde ich die issue nun erstmal schliessen bis auf weiteres
