### ISSUE TITLE
HTML Code sehr unschön im Menü

### ISSUE THREAD

**Issue by DO1JLR** [ToolboxBodensee/toolbox-webseite#375]
```html

                 <li><a href="./blog/">Blog</a>
                    <ul>
                      
                        
                          <li>
                            <a href="./blog/secure-shell/">
                              Secure Shell
                            </a></li>
                        
                          <li>
                            <a href="./blog/seeboerse-zum-anfassen/">
                              Seebörse
                            </a></li>
                        
                          <li>
                            <a href="./blog/camp19/">
                              Technik Camp
                            </a></li>
                        
                          <li>
                            <a href="./blog/tuer19/">
                              Offene Tür 2019
                            </a></li>
                        
                          <li>
                            <a href="./blog/report_jahreshauptversammlung_2019/">
                              JHV 2019
                            </a></li>
                        
                          <li>
                            <a href="./blog/git-init/">
                              How 2 git
                            </a></li>
                        
                          <li>
                            <a href="./blog/kinder-basteln-fledermauskasten/">
                              Fledermauskasten
                            </a></li>
                        
                      
                      
                        
                          <li><a href=./blog/
                            >
                            - Alle Blogeinträge -
                          </a></li>
                        
                          <li><a href=./feed_blog.xml
                            >
                            RSS Feed
                          </a></li>
                        
                      
                    </ul>
                  </li>
                
                        
```

Sollte man mal etwas umschreiben... Ähnlich wie beim [C3WOC](https://github.com/c3woc/c3woc-website/blob/master/templates/layout.html#L110-L165) bereits geschehen!

Beispiel in schöner *(vom C3WOC)*:
```html
                   <li><a href="/blog">Blog</a>
                      <ul>
                            <li>
                              <a href="/blog/erster-analoger-waffelzaehler/">analoger Waffelzähler</a></li>
                            <li>
                              <a href="/blog/we-need-you-at-gpn19/">[GPN] We need you</a></li>
                            <li>
                              <a href="/blog/binary-waffles/">binary waffles</a></li>
                            <li>
                              <a href="/blog/eh19/">Osterwaffel</a></li>
                            <li>
                              <a href="/blog/chaospott-macht-waffeln/">Chaospottwaffeln</a></li>
                            <li>
                              <a href="/blog/cep19/">CEP19</a></li>
                            <li>
                              <a href="/blog/tb-doenerwaffel/">Dönerwaffel</a></li>
                         <li><a href=/blog/>Alle Beiträge</a></li><li><a href=/feed_blog.xml>RSS Feed</a></li>
                      </ul>
                    </li>
```

**Comment by maxbachmann** [comment]
Es wäre ein guter Anfang wenn du mit reinschreibst von welcher Datei du spricht
Dann muss das nicht jeder selbst suchen

**Comment by maxbachmann** [comment]
Edit: ich konnte es spontan nicht am Handy finden, schaue es mir aber gern an wenn du da Genauere Angaben machst wo sich das findet (ist das ein template?)

**Comment by DO1JLR** [comment]
> Es wäre ein guter Anfang wenn du mit reinschreibst von welcher Datei du spricht
> Dann muss das nicht jeder selbst suchen

Ich spreche von der Datei, die ich mit dem Titel "C3WOC" verlinkt habe als Beispiel, wie es bei C3WOC aussieht...

Hier also nochmal für die langsmaeren Browser:

```
# Schlechte Version:
https://github.com/ToolboxBodensee/toolbox-webseite/blob/2b4d1e1525c48be5d4bb21d7a399fc6b414b3d3b/templates/layout.html#L114-L143

# nicht ganz so schlechte Version:
https://github.com/c3woc/c3woc-website/blob/master/templates/layout.html#L110-L165
```

**Comment by maxbachmann** [comment]
Ok ich kümmere mich drum

**Comment by maxbachmann** [comment]
@DO1JLR 
Ich würde gern auch das template besser lesbar machen. Hierbei ergibt sich ein Problem wenn ich sowohl html als auch template lesbar halten will, kann ich ja nicht beliebig einrücken. Es gibt da meiner Ansicht nach mehrere Optionen die ich mal kurz vorstelle anhand eines Beispiels 
```html
                {%- if  bag('nav-bar', title) %}
                {%- for nav_title, nav_url in bag('nav-bar', title).items() %}
                <li>
                  <a href={{ nav_url if 'http' in nav_url else nav_url|url }}
                  {%- if bag('nav-bar', 'button', nav_title) %}class="button nav"
                  {%- endif %}>{{ bag('navigation', this.alt, nav_title)
                    if bag('navigation', this.alt, nav_title) 
                    else bag('navigation', 'de', nav_title) }}</a>
                </li>
                {%- endfor %}
                {%- endif %}
```
```html
{%- if  bag('nav-bar', title) %}
  {%- for nav_title, nav_url in bag('nav-bar', title).items() %}
                <li>
                  <a href={{ nav_url if 'http' in nav_url else nav_url|url }}
    {%- if bag('nav-bar', 'button', nav_title) -%}
                  class="button nav"
    {%- endif -%}
                    >{{ bag('navigation', this.alt, nav_title)
                    if bag('navigation', this.alt, nav_title) 
                    else bag('navigation', 'de', nav_title) }}</a>
                </li>
  {%- endfor %}
{%- endif %}
```
```html
{%- if  bag('nav-bar', title) %}
  {%- for nav_title, nav_url in bag('nav-bar', title).items() %}
                <li>
                  <a href={{ nav_url if 'http' in nav_url else nav_url|url }}
                  {%- if bag('nav-bar', 'button', nav_title) %}class="button nav"
                  {%- endif %}>{{ bag('navigation', this.alt, nav_title)
                    if bag('navigation', this.alt, nav_title) 
                    else bag('navigation', 'de', nav_title) }}</a>
                </li>
  {%- endfor %}
{%- endif %}
```
In Option 1 wird insbesondere bei tieferer Verschachtelung das Template echt schlecht lesbar. Daher tendiere ich zu Option 2/3. Welche Option bevorzugst du oder hast du eine Idee, die das Ganze nochmal besser lesbar macht?

**Comment by DO1JLR** [comment]
> In Option 1 wird insbesondere bei tieferer Verschachtelung das Template echt schlecht lesbar. Daher tendiere ich zu Option 2/3. Welche Option bevorzugst du oder hast du eine Idee, die das Ganze nochmal besser lesbar macht?

Ich würde keine der Optionen machen oder für gut heißen.

Denn egal wie du das hier aufsplittest haben wir da eine enorme ansammlung an whitespaces und newlines (``␤``) im gerenderten HTML für den Preis, dass das template halbwegs ordentlich aussieht.

Beispiel im Template:
```j2
{% if  bag('nav-bar', title) %}
  {% for nav_title, nav_url in bag('nav-bar', title).items() %}
    <a>Hallo Welt</a>
  {% endfor %}
{% endif %}
```
Gerendertes HTML:
```html
␤
␤
<a>Hallo Welt</a>
␤
␤
```

Was ICH hier vorschlagen würde ist, dein Template so lesbar wie möglich zu schreiben... Aber eben die controll charakter zu verschieben.

Beispiel Template:
eispiel im Template:
```j2
{% if  bag('nav-bar', title) %}{% 
       for nav_title, nav_url in bag('nav-bar', title).items() 
%}<a>Hallo Welt</a>{%
       endfor %}{%
    endif %}
```
Gerendertes HTML:
```html
<a>Hallo Welt</a>␤
```
-> Das sieht jetzt nicht so ganz lesbar aus. Das könnte man auch anders gestalten mit mehr Kommentaren oder so... Beispiel:
```j2
{# BEGINN EINER IF SCHLEIFE MIT FOR SCHLEIFE #}{% 
  if  bag('nav-bar', title) %}{% 
    for nav_title, nav_url in bag('nav-bar', title).items() 
%}<a>Hallo Welt</a>{%
    endfor %}{%
  endif %}{#
# ENDE EINER IF SCHLEIFE MIT FOR SCHLEIFE #}
```

Aber deine varrianten scheinen mir alle nicht das angesprochene problem zu lösen. Sorry!

**Comment by DO1JLR** [comment]
Was mir hier wichtig ist, wäre das als ergebnis ein sauberer HTML Code rauskommt.

Mit ordentlichen Einrückungen. Oder minimized. Oder wie auch immer man das machen möchte.

Aber nicht mit hundert tausend Neuen zeilen.

**Comment by maxbachmann** [comment]
@DO1JLR Es geht hier gerade um die Lesbarkeit des templates und da gefällt mir diese Lösung nicht

Btw jedes der von mir gezeigten Beispiele ergibt exakt den gleichen HTML code ;)
Der Trick ist hierbei, dass den Leuten bei jinja2 natürlich klar ist, dass das mit den leeren Zeilen iwie doof ist und die von dir gezeigte Lösung zwar funktioniert aber nicht optimal in Bezug auf die Lesbarkeit ist
Aus diesem Grund gibt es bei jinja2 die Option whitespaces zu entfernen durch die Verwendung der Bindestrichs wie in meinen Beispielen.
zB
```html
{% if ... -%}
  Test
{%- endif %}
```
Erzeugt die Ausgabe
```html
Test
```

Daher ergibt sich durchaus die Frage wie das templates am Besten lesbar ist. Die Version die aktuell in meinem Pullrequest steht hat bereits an einigen mehr Stellen eine korrekte Einrückung der html Syntax ohne leere Zeilen als die Version des C3WOC ;)

**Comment by DO1JLR** [comment]
OK, cool.

man lernt immer etwas dazu :stuck_out_tongue_winking_eye:

**Comment by maxbachmann** [comment]
Ja ist ein recht unbekanntes aber super cooles feature

**Comment by maxbachmann** [comment]
@D01JLR bleibt die Frage welche Option du für das Template für am Besten lesbar hältst ;)

**Comment by DO1JLR** [comment]
2
======

**Comment by maxbachmann** [comment]
@DO1JLR 
Ich werde das Problem mit dem html code jetzt auf zwei Wege angehen.
Erstens: Schonmal möglichst schönen code erzeugen durch das template, wobei das nicht an jeder Stelle optimal möglich ist.
Zweitens: Ein Plugin für Lektor schreiben, welches einen html beautifier nutzt um die ausgegebenen html files aufzuhübschen ;) (der html beautifier kommt dann auch in PyPI, so dass wir ihn gleich bei allen Webseiten einfach nutzen können)

**Comment by maxbachmann** [comment]
fixed
