### ISSUE TITLE
branch "snips" als pull request einreichen

### ISSUE THREAD

**Issue by DO1JLR** [ToolboxBodensee/toolbox-webseite#383]
@maxbachmann hier als erinnerung für dich!

ist ein paar monate älter als meine nicht fertigen dinge an der webseite.

Wenn du hier mit ansprüchen kommst, kann ich das auch.

**Comment by maxbachmann** [comment]
Ich bin für den aktuell offenen Pull Request noch aktiv dabei, da mir der entsprechenden Inhalt eigentlich wichtig ist. Du hast aber Recht, dass ich den entsprechenden Artikel dann irgendwann auch gleich neu verfassen kann. Ich habe daher den Branch entfernt
