### ISSUE TITLE
imagemagick error

### ISSUE THREAD

**Issue by maxbachmann** [ToolboxBodensee/toolbox-webseite#393]
Imagemagick wirft aktuell eine Fehlermeldung für diese png. Ich habe persönlich keine Ahnung woran das genau liegt, aber das sollte man mal noch fixen.

```bash
convert: iCCP: CRC error `/home/travis/build/ToolboxBodensee/toolbox-webseite/content/projekte/the-best-game/best_game.png' @ warning/png.c/MagickPNGWarningHandler/1752.
```

**Comment by drwuro** [comment]
habe das gerade mal auf der kommandozeile nachgestellt, da fliegt bei mir auch der error. wenn ich das PNG allerdings mit gimp neu abspeichere (oder einfach mit convert ohne parameter erneut in eine neue PNG-datei schreibe) dann bekomme ich eine datei die keinen fehler mehr wirft. ich wuerde allerdings sagen wir ersetzen das bild gleich durch ein groesseres. ich kann das grad mal machen...

**Comment by drwuro** [comment]
sollte nun gefixt sein...

**Comment by maxbachmann** [comment]
gefixt
