### ISSUE TITLE
Bilder sind weg

### ISSUE THREAD

**Issue by DO1JLR** [ToolboxBodensee/toolbox-webseite#396]
Bei den Blogposts sind alle Bilder weg.

**Comment by maxbachmann** [comment]
oh ...
spontan sieht das nach template stuff aus (also wohl meine Schuld)

**Comment by DO1JLR** [comment]
> oh ...
> spontan sieht das nach template stuff aus (also wohl meine Schuld)

Jep. 

Hab das mal versucht zu fixen!

**Comment by maxbachmann** [comment]
danke

**Comment by DO1JLR** [comment]
Jo, kein ding.

Jetzt muss dieses Travis.org nur noch machen.

Schade, dass bei Cloudflare ausfällen das travis.com immer bevorzugt behandelt wird...

@maxbachmann Kannst du da nicht was machen?
