### ISSUE TITLE
Projekte sind nicht richtig ausgerichtet

### ISSUE THREAD

**Issue by maluramichael** [ToolboxBodensee/toolbox-webseite#4]
![toolbox cyber yt_projekte_](https://user-images.githubusercontent.com/1489383/45157602-e99df000-b1e1-11e8-9d23-104108d444c8.png)

Man sieht in der ersten Reihe wie die Projekte nach unten abfallen.

**Comment by DO1JLR** [comment]
@maluramichael Hast du noch mehr Infos und Meta-Daten dazu? 
Unter Firefox 61.0.2 (64-bit) auf einem Arch-Linux kann ich das nicht reproduzieren.

![screenshot_2018-09-06 projekte](https://user-images.githubusercontent.com/16953664/45166291-f6790e80-b1f6-11e8-9465-fa4cf365cd3a.png)

**Comment by maluramichael** [comment]
Nutze Debian stretch und chrome 69.

**Comment by phschoen** [comment]
schein chrome und chomium spezifisch zu sein Firefox funktioniert

**Comment by DO1JLR** [comment]
Beim Setzen von ``.box{ box-sizing: border-box;}`` nach ``box{ box-sizing: initial; }`` sind nur noch zwei Projekte nebeneinander, allerdings auf gleicher höhe... 
Sieht aber nicht so geil aus...

**Comment by ottojo** [comment]
closed in #26
