### ISSUE TITLE
No MGH Copter Project

### ISSUE THREAD

**Issue by haekelhexe** [ToolboxBodensee/toolbox-webseite#426]
@phschoen @DEvil0000 - da könnte auch mal was zu geschrieben werden. 
Mach ich gern in allen Sprachen, brauch aber den technischen/zeitlichen/inhaltlichen Input von euch.

**Comment by DO1JLR** [comment]
https://www.suedkurier.de/region/bodenseekreis/markdorf/Loeten-bis-zum-Abheben-So-bauen-Maedchen-in-Markdorf-einen-flugfaehigen-Quadrocopter;art372484,10125455

Hier wäre ein fertiger Text dazu...

**Comment by haekelhexe** [comment]
Done
