### ISSUE TITLE
XHR Scripte von extern

### ISSUE THREAD

**Issue by DO1JLR** [ToolboxBodensee/toolbox-webseite#440]
Wir haben wohl wieder etwas von externer Quelle eingefangen....

Das müsste dann mal weg oder selber gehostet werden!!!

![sh1t](https://user-images.githubusercontent.com/16953664/65435315-9ca6af00-de20-11e9-8f54-8a2e41ccf875.jpg)

**Comment by re4jh** [comment]
das is kein shit, das ist ein xhr-call auf die space-api bei der see-base.
(von dort kann ich den door-state dynamisch einlesen.)

vorübergehend könnte man das solange beide websites (noch?) zufällig auf dem selben server liegen auch als symlink anbieten oder zukünftig per wget-cronjob lokal cachen und dann natürlich nur vom eigenen server zuzeln.

lösungsweg:
der wgetter, den du dafür anlegen müsstest, sollte mir am besten minütlich die https://bodensee.space/spaceapi/toolboxbodenseeev.json in den selben webroot packen.
leg mir das bitte als cronjob an, verrat mir den pfad und dann kann gerne wieder gerne auf externe calls verzichtet werden.

**Comment by DO1JLR** [comment]
andere idee...

wir lassen die konstruktion so, dass die spaceapi auf dem selben server läuft wie die webseite.... auch nach dem umzug!

Bis dahin könntest du auch https://toolbox-bodensee.de/toolboxbodenseeev.json verwenden...

**Comment by re4jh** [comment]
und du hälst die jetzt synchron? wie? symlink?

**Comment by re4jh** [comment]
nur für dich hab ich den zu 2/3 teuflischen pull request gemacht:
https://github.com/ToolboxBodensee/toolbox-webseite/pull/444

**Comment by DO1JLR** [comment]
genau. ist ein symlink auf den anderen webspace wo das mit diesem bash cgi script gedöns generiert wird

**Comment by re4jh** [comment]
na dann können wir das issue hier ja zumachen
