### ISSUE TITLE
Mitgliederliste

### ISSUE THREAD

**Issue by maluramichael** [ToolboxBodensee/toolbox-webseite#5]
Ich faende eine Mitgliederliste toll. Damals wurden in der Liste auch alle Ehrenmitglieder und Spender angezeigt.

**Comment by blaues0cke** [comment]
Würde aber sagen, maximal für Sponsoren - sonst haben wir wieder dieses DSGVO-Thema

**Comment by maluramichael** [comment]
Ja und vielleicht wer will kann sich ja ueber einen PR selbst hinzufuegen. Ich zb hab kein Problem damit.

**Comment by DO1JLR** [comment]
Gibt es denn so eine Liste irgendwo? Das man die Daten zumindest irgendwo her bekommt?

**Comment by maluramichael** [comment]
Schon klar 😊 ich schau mir bald mal an wie man damit collections erstellen kann.

**Comment by tschanne** [comment]
Es wurde mal entschieden, die Mitgliederliste NICHT zu machen. Weil sie eh nach einer Woche falsch ist und keiner Lust hat sie zu pflegen.
Sponsoren haben meines Wissen explizit darum gebeten, NICHT ins Internet eingetragen zu werden (mit der Befürchtung, dann können sie sich vor Anfragen anderer Vereine nicht mehr retten).

**Comment by maluramichael** [comment]
@tschanne  alles klar. Dann mach ich mal hier zu.
