### ISSUE TITLE
Menü auf Startseite sollte feststehend sein.

### ISSUE THREAD

**Issue by 205er** [ToolboxBodensee/toolbox-webseite#57]
Moin!

Die Menüleiste auf der Startseite ist nicht feststehend, so wie das auf allen anderen Seiten der Fall ist. Das führt dazu, dass man nach durchscrollen der Startseite etwas verloren am unteren Ende der Page ankommt und nicht so richtig weiß wie es weiter geht.

Vorschlag:
- Entweder die Menüleiste konsequent auf allen Seiten feststehend machen oder
- in jedem Teilbereich der Startseite einen "bring mich nach oben"-Button einfügen.

**Comment by marekgebka** [comment]
Ich schaue es mir mal an. Würde den Header auch sticky machen, wie auf den anderen Seiten. Dann ist es einheitlich.

**Comment by 205er** [comment]
Mit https://github.com/ToolboxBodensee/toolbox-webseite/pull/81 gefixt! Danke!!!
