### ISSUE TITLE
Menü Dropdown Hover unzuverlässig

### ISSUE THREAD

**Issue by xythobuz** [ToolboxBodensee/toolbox-webseite#61]
Wird die Maus schnell über die Menüeinträge geschoben und dabei ein "TouchDown" event erzeugt während die Fade-In Animation des Dropdown Menüs noch läuft wird das Dropdown Menü des aktuell mit der Maus markierten Eintrags nicht angezeigt. Das Problem tritt insbesondere mit Laptop Trackpads häufig auf...

Wird da eventuell irgend ein Handler im JS erst zu spät registriert? Könnte da die (etwas veraltete?) jQuery oder Dropotron Version Schuld sein?

**Comment by maxbachmann** [comment]
sollte mit dem reinen css menü jetzt funktionieren
