### ISSUE TITLE
Accessibility für Menü-Einträge / Übersichtsseiten

### ISSUE THREAD

**Issue by xythobuz** [ToolboxBodensee/toolbox-webseite#62]
Im Moment herrscht etwas Uneinigkeit bei den verschiedenen Menüeinträgen oben auf der Webseite.

Beim Hovern auf "Projekte" oder "Verein" werden Menüs mit vielen Unterseiten angezeigt, gleichzeitig führt aber der Link selbst auf eine eigene Unterseite. Im Fall der Projekte ist diese Unterseite einfach eine Übersicht aller weiteren Projekte. Damit können auch User ohne Dropdown-Support im Browser alle Projekte erreichen.

Bei "Verein" fehlt diese Übersichtsseite. Wenn in meinem Browser das Dropdown Menü nicht funktioniert kann ich z.B. die Seite "Elektrowerkstatt" überhaupt nicht erreichen...?

Ich denke wir brauchen für "Verein" eine ähnliche Übersichtsseite wie für "Projekte"... Meinungen oder alternative Ideen? :smile:

**Comment by 205er** [comment]
Sehe ich genauso! sollten wir konsequent einheitlich gestalten.
Der Menüpunkt "Impressum" hat bspw. eine Sub page "Impressum". Warum doppelt?

**Comment by DO1JLR** [comment]
Sollte jetzt Übersichtlicher sein!
