### ISSUE TITLE
Vereinsheim offen/geschlossen-Indikator wird fehlerhaft angezeigt

### ISSUE THREAD

**Issue by 205er** [ToolboxBodensee/toolbox-webseite#69]
Die Info oben links, über die ausgegeben wird, ob das Vereinsheim geöffnet oder geschlossen ist, wird fehlerhaft angezeigt. Siehe Screenshot.

![2018-09-27 17_04_40-toolbox bodensee e v](https://user-images.githubusercontent.com/14996169/46155634-0b861200-c278-11e8-9f8b-88b9fe291b74.png)

**Comment by 205er** [comment]
Das passiert auch auf der Karte...
![image](https://user-images.githubusercontent.com/14996169/46155750-52740780-c278-11e8-8b21-060e0ee683ca.png)

**Comment by xythobuz** [comment]
Öh, mehr Infos bitte... Browser? Device? OS?
Ich kann das hier nicht reproduzieren...

**Comment by 205er** [comment]
![image](https://user-images.githubusercontent.com/14996169/46156802-96680c00-c27a-11e8-9c41-d0468837fcbf.png)

**Comment by xythobuz** [comment]
Also unter Linux & Firefox ist bei mir alles wie gewünscht.
Could not reproduce :stuck_out_tongue:

**Comment by 205er** [comment]
Problem erkannt:

https://bodensee.space/spaceapi/toolbox/spacestatus.css kann nicht geladen werden, weil die Domain hier im Netz (immer mal wieder) geblockt wird...
Sorry, für die Verwirrung. Vielleicht könnte man das CSS file ja auf dem TB-Server unterbringen.

**Comment by xythobuz** [comment]
Na dann @DO1JLR kannst du das entsprechend wie mit der ics datei umbiegen?

**Comment by DO1JLR** [comment]
Nein, irgendwie mag mich da der Apache gerade nicht.
Muss sich @mart-ffbsee mal anschauen. Da hat sich mit einer neuen Apache version irgend was geändert!

**Comment by DO1JLR** [comment]
Fixed by https://github.com/ToolboxBodensee/toolbox-webseite/commit/a3b16187646f9a484ac4a33eca952e62ffaeb095
