### ISSUE TITLE
Fade-In auf der Hauptseite beschleunigen

### ISSUE THREAD

**Issue by maluramichael** [ToolboxBodensee/toolbox-webseite#8]
Ich wuerde die Transition beschleunigen. Macht die ganze Seite gefuehlt schneller.

**Comment by DO1JLR** [comment]
@maluramichael gerne. Pull Requests stehen jedem offen. 
Meine JavaScript Skills hören da aber leider auf

**Comment by maluramichael** [comment]
Hab schon ein wenig gesucht. Glaube das liegt irgendwo im css.

**Comment by phschoen** [comment]
see pullrequest #13

**Comment by maluramichael** [comment]
Merci
