### ISSUE TITLE
Projekte - Aufteilung und Sortierung

### ISSUE THREAD

**Issue by 205er** [ToolboxBodensee/toolbox-webseite#85]
Moin,

kann man die Sortierung der Projekte in auf der [Übersichtsseite](https://toolbox-bodensee.de/projekte/) sowie im Menü beeinflussen?

Verbesserungsvorschlag:
Warum nicht alle Projekte auf einer Seite aufführen!? Die Verteilung auf mehrere Seiten führt u.U. dazu, dass einige, durchaus sehr tolle Projekte untergehen bzw. übersehen werden. Könnte man ja auch so gestalten, dass die Liste beim Scrollen nachgeladen wird. (ist der User also das Ende des Viewport angekommen, wird Content nachgeladen, so wie man dass von diversen social media-Plattformen kennt und gewohnt ist)
Aus meiner Sicht spricht aber auch nichts gegen eine lange, statische Liste. So viele Projektseiten gibt's ja nun auch nicht ;-)

**Comment by ottojo** [comment]
Momentan ist die Liste nach Datum und Name sortiert ([hier](https://github.com/ToolboxBodensee/toolbox-webseite/blob/14483371fb2df6c66e867ddeaa4583d99635c70e/models/projekte.ini#L20))
Finde ich ok so, aber das mit der pagination finde ich auch nicht so optimal.
