### ISSUE TITLE
Fehlendes lade-icon

### ISSUE THREAD

**Issue by ottojo** [ToolboxBodensee/toolbox-webseite#86]
Beim laden der Webseite ist ein sich drehendes viereck zu sehen, ich vermute mal da fehlt ein icon oder so

**Comment by DO1JLR** [comment]
Das kommt vermutlich noch von der Umstellung von Font Awesome 4 auf 5

**Comment by marekgebka** [comment]
Soll ich mir das mal anschauen?

**Comment by 205er** [comment]
@marekgebka Unbedingt!

**Comment by DO1JLR** [comment]
Tahnks to @marekgebka https://github.com/ToolboxBodensee/toolbox-webseite/pull/91
