### ISSUE TITLE
Automatically generate CSS from SASS

### ISSUE THREAD

**Issue by DO1JLR** [ToolboxBodensee/toolbox-webseite#87]
It would be nice to generate the CSS based on the SASS from ansible ans not manually by sassc.

**Comment by DO1JLR** [comment]
Da scheint es etwas zu geben... Aber dieses npm und nodejs kapiere ich nicht ganz: https://www.getlektor.com/docs/guides/webpack/

@blaues0cke Kannst du hier eventuell weiter helfen?
*Es würde ja reichen, wenn zumindes das travis damit richtig umgehen kann...*

**Comment by fabsb** [comment]
@DO1JLR gibt es eine Möglichkeit, vor dem deployen einen Docker Container auszuführen, der die Assets baut? Falls ja, ist schnell gemacht.

**Comment by fabsb** [comment]
Oder spricht was dagegen, generell Docker für CI einzusetzen?

Da *lektor* python braucht und für *webpack* JavaScript (nodejs) erforderlich ist und Travis nicht so einfach mit mehrere Sprachen in einem Projekt umgehen kann, könnte man zum bauen und deployen Docker mit Travis nutzen.

**Comment by DO1JLR** [comment]
Ich hab bisher wenig erfahrung mit der zusammenarbeit von travis und docker...
Wenn du meinst das geht... Gerne ausprobieren und umsetzen!
