### ISSUE TITLE
Font-Awesome auch bei deaktivierten JavaScript

### ISSUE THREAD

**Issue by DO1JLR** [ToolboxBodensee/toolbox-webseite#90]
Einige Menschen rufen die Webseite mit deaktivierten javaScript auf. Das kann durch das Installieren diverser Plugins erfolgen oder aber auch auf dem Handy durch das verwenden von Beispielsweise [Firefox Klar](https://support.mozilla.org/de/kb/was-ist-firefox-klar).

Es wäre cool, diesen Menschen trotzdem Icons zu präsentieren. Ich hab aber keine Ahnung ob das wirklich gehen kann... 

Eine Alternative wäre wohl auch [hier beschrieben mit svg-sprites](https://fontawesome.com/how-to-use/on-the-web/advanced/svg-sprites). Müsste man sich anschauen wie einfach das geht...

**Comment by fabsb** [comment]
@DO1JLR Font-Awesome braucht im Normalfall kein JavaScript sondern wird in SCSS/CSS als Webfont eingebunden.

Hab die Website in aktuellen Firefox, Chrome und Safari bei deaktivierten JavaScript getestet und die Icons werden angezeigt. Unter Umständen kann es sein, dass ein Browser fremde Fonts nicht laden will und das kann durchaus dazu führen, dass die Icons nicht angezeigt werden. Ist das das eigentliche Problem?

Nachteil von SVG-Icons ist, dass Browser auf mobilen Geräten mehr CPU/GPU braucht um SVG zu rendern. 

Wollen wir trotzdem Font-Awesome als SVG-Sprites einbinden?

**Comment by maxbachmann** [comment]
@DO1JLR Ich stecke da nicht so tief drin. 
Daher mal als Gegenfrage:
Was für einen Vorteil hätte den der Wechsel zu SVG-Sprites?

**Comment by DO1JLR** [comment]
@maxbachmann Ich erhoffe mir hierbei, das auch bei agressiver eingesetellten Werbeblockern die Icons standardmäßig angezeigt werden. Ob das aber wirklich funktioniert... keine Ahnung!

**Comment by DO1JLR** [comment]
#216
