### ISSUE TITLE
Freifunk Projekt

### ISSUE THREAD

**Issue by maxbachmann** [ToolboxBodensee/toolbox-webseite#98]
Offenbar sind mehrere der links in dem Projekt nicht mehr gültig

**Comment by maxbachmann** [comment]
https://freifunk-bodensee.net/start.html, sowie
https://freifunk-bodensee.net/lib/tpl/dokuwiki-template/images/logo.svg 
sind die ungültigen links

**Comment by 205er** [comment]
@DO1JLR : die URL https://freifunk-bodensee.net/start.html bitte auch noch abändern.

**Comment by DO1JLR** [comment]
Ist gefixt, danke
